services:
  project-service:
    build:
      context: .
      target: development
    container_name: project_service
    restart: unless-stopped
    ports:
      - "12000:12000"
    env_file:
      - .env
    networks:
      - gazella-net

networks:
  gazella-net:
    external: true
